// Maintainer-only tool. Syncs files from a flutter_reference checkout into
// the brick's __brick__ tree, applying per-file token substitutions.

import 'dart:io';

import 'package:args/args.dart';
import 'package:path/path.dart' as p;

const _brickRoot = '__brick__/{{project_name.snakeCase()}}';

// Paths (relative to source root) that are never copied.
// Entries ending in `/` match a directory prefix; otherwise an exact path.
const _excludePrefixes = <String>[
  // Build / dependency artefacts (regenerated by tooling).
  // pubspec.lock is deliberately NOT here: this is an app template, not a
  // library, so generated projects should start on the exact dependency set
  // the reference was tested against. Without it `pub get` resolves latest-
  // compatible at generation time and the template rots silently — a dio
  // minor bump adding an enum value is enough to break an exhaustive switch.
  '.dart_tool/',
  'build/',
  '.flutter-plugins-dependencies',

  // Native platform dirs (regenerated by `flutter create .` in post_gen).
  'android/',
  'ios/',
  'web/',
  'linux/',
  'macos/',
  'windows/',

  // Per-deployment / sensitive.
  'env/',

  // Brick-meta / source-only docs.
  'docs/pending.md',
  'docs/template-purpose.md',
  'docs/superpowers/',

  // Hand-authored brick files (live in __brick__/, never overwrite from source).
  'README.md',

  // Source-repo working state, not for consumer projects.
  'CLAUDE.md',

  // Tool / IDE state.
  '.git/',
  '.idea/',
  '.vscode/',
  '.claude/',

  // Auto-regenerated by `flutter create .` in post_gen.
  'devtools_options.yaml',
];

// File-extension excludes (regenerated by build_runner / IDE tooling).
const _excludeSuffixes = <String>[
  '.g.dart',
  '.freezed.dart',
  '.iml',
];

class _Rule {
  _Rule(this.match, this.replacements);

  // Predicate over relative path (POSIX-style).
  final bool Function(String relPath) match;
  final List<(String from, String to)> replacements;
}

bool Function(String) _isExactMatch(String exact) =>
    (String path) => path == exact;

bool _isDartFile(String path) => path.endsWith('.dart');

// Free-text vars (description, app_name) use the triple-mustache form:
// mason HTML-escapes `{{var}}`, so an `&` in the value would reach
// generated source as `&amp;`. Identifier-shaped vars don't need it.
final List<_Rule> _rules = [
  _Rule(
    _isExactMatch('pubspec.yaml'),
    const [
      ('name: flutter_reference', 'name: {{project_name.snakeCase()}}'),
      ('description: "A new Flutter project."', 'description: {{{description}}}'),
    ],
  ),
  _Rule(
    _isDartFile,
    const [
      ('package:flutter_reference/', 'package:{{project_name.snakeCase()}}/'),
    ],
  ),
  _Rule(
    _isExactMatch('lib/app.dart'),
    const [
      ("title: 'App',", "title: '{{{app_name}}}',"),
    ],
  ),
  _Rule(
    _isExactMatch('lib/core/env/env.dart'),
    const [
      ("'io.logto://callback'", "'{{auth_redirect_scheme}}://callback'"),
      ("'io.logto://home'", "'{{auth_redirect_scheme}}://home'"),
    ],
  ),
  // The two replacements below produce the same result regardless of order,
  // because the `package:flutter_reference/` token's tail expansion equals
  // the bare-`flutter_reference` substitution. Keep the prefix-rule first so
  // a future divergence (e.g. distinct brick var for the package import path)
  // doesn't silently produce wrong output.
  _Rule(
    _isExactMatch('docs/template-foundations.md'),
    const [
      ('package:flutter_reference/', 'package:{{project_name.snakeCase()}}/'),
      ('flutter_reference', '{{project_name.snakeCase()}}'),
      // Same rewrite as lib/core/env/env.dart above: the doc quotes those
      // defaults, and the reference hardcodes the brick's old io.logto value.
      ('io.logto://callback', '{{auth_redirect_scheme}}://callback'),
      ('io.logto://home', '{{auth_redirect_scheme}}://home'),
    ],
  ),
];

bool _isExcluded(String relPath) {
  for (final prefix in _excludePrefixes) {
    if (relPath == prefix) return true;
    if (prefix.endsWith('/') && relPath.startsWith(prefix)) return true;
  }
  for (final suffix in _excludeSuffixes) {
    if (relPath.endsWith(suffix)) return true;
  }
  return false;
}

Future<void> main(List<String> args) async {
  final parser = ArgParser()
    ..addOption('source', help: 'Path to flutter_reference checkout. Defaults to ../flutter_reference.')
    ..addFlag('dry-run', defaultsTo: false, help: 'Preview without writing.')
    ..addFlag('help', abbr: 'h', defaultsTo: false, negatable: false);

  final argv = parser.parse(args);
  if (argv['help'] as bool) {
    stdout.writeln('Usage: dart run tool/sync.dart [options]\n');
    stdout.writeln(parser.usage);
    return;
  }

  final scriptDir = Directory.current;
  final source = Directory(p.normalize(p.absolute(
    (argv['source'] as String?) ?? p.join(scriptDir.path, '..', 'flutter_reference'),
  )));
  final dryRun = argv['dry-run'] as bool;

  if (!source.existsSync()) {
    stderr.writeln('Source directory not found: ${source.path}');
    exit(1);
  }

  await _verifySource(source);

  final brickOut = Directory(p.join(scriptDir.path, _brickRoot));

  if (!dryRun) {
    await _wipeSyncedSubtrees(brickOut);
  }

  // Collect + sort entities so iteration order is reproducible across runs.
  final files = <File>[];
  await for (final entity in source.list(recursive: true, followLinks: false)) {
    if (entity is File) files.add(entity);
  }
  files.sort((a, b) => a.path.compareTo(b.path));

  final stats = _Stats();
  for (final entity in files) {
    final relPath = p.relative(entity.path, from: source.path).replaceAll(r'\', '/');
    if (_isExcluded(relPath)) {
      stats.skipped++;
      continue;
    }

    if (dryRun) {
      // Don't read or transform in dry-run; we'd hit decode errors on any
      // non-UTF-8 file the rules don't cover, and we'd never write the result.
      stats.copied++;
      continue;
    }

    final String content;
    try {
      content = await entity.readAsString();
    } catch (e) {
      stderr.writeln('Failed to read $relPath as UTF-8: $e');
      stderr.writeln('Add the path to _excludePrefixes / _excludeSuffixes if it is not text.');
      exit(1);
    }
    final transformed = _applySubstitutions(relPath, content);

    final destPath = p.join(brickOut.path, relPath);
    final destFile = File(destPath);
    await destFile.parent.create(recursive: true);
    await destFile.writeAsString(transformed);
    stats.copied++;
  }

  stdout.writeln('Sync ${dryRun ? '(dry-run) ' : ''}complete: ${stats.copied} files written, ${stats.skipped} skipped.');
  if (!dryRun) {
    stdout.writeln('\nDiff in based_flutter:');
    final res = await Process.run('git', ['status', '--short'], workingDirectory: scriptDir.path);
    stdout.write(res.stdout);
  }
}

Future<void> _verifySource(Directory source) async {
  final pubspec = File(p.join(source.path, 'pubspec.yaml'));
  if (!pubspec.existsSync()) {
    stderr.writeln('Source has no pubspec.yaml: ${source.path}');
    exit(1);
  }
  final content = await pubspec.readAsString();
  if (!content.contains('name: flutter_reference')) {
    stderr.writeln('Source pubspec.yaml does not declare name: flutter_reference (got: ${source.path})');
    exit(1);
  }
}

// Partial wipe: only the subtrees that should mirror flutter_reference exactly
// are cleared before re-copy. Other paths in the brick output (hand-authored
// README.md, env/example.json, plus single-file syncs like pubspec.yaml that
// always get overwritten) are preserved. If the source repo deletes a file
// outside lib/ or docs/template-foundations.md, the brick output may retain
// the stale copy — `git status --short` at the end of main() exposes such
// orphans for the maintainer to remove manually.
Future<void> _wipeSyncedSubtrees(Directory brickOut) async {
  final lib = Directory(p.join(brickOut.path, 'lib'));
  if (lib.existsSync()) {
    await lib.delete(recursive: true);
  }
  final foundationsDoc = File(p.join(brickOut.path, 'docs', 'template-foundations.md'));
  if (foundationsDoc.existsSync()) {
    await foundationsDoc.delete();
  }
}

String _applySubstitutions(String relPath, String content) {
  var out = content;
  for (final rule in _rules) {
    if (!rule.match(relPath)) continue;
    for (final (from, to) in rule.replacements) {
      out = out.replaceAll(from, to);
    }
  }
  return out;
}

class _Stats {
  int copied = 0;
  int skipped = 0;
}
