name: {{project_name.snakeCase()}}

description: {{{description}}}

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_seed_scheme: ^4.0.1
  flutter_riverpod: ^3.3.1
  dio: ^5.9.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  drift: ^2.31.0
  drift_flutter: ^0.3.1
  path_provider: ^2.1.5
  talker: ^5.1.17
  talker_dio_logger: ^5.1.17
  talker_riverpod_logger: ^5.1.17
  talker_flutter: ^5.1.16
  auto_route: ^11.1.0
{{#auth}}  logto_dart_sdk: ^4.0.0
  flutter_secure_storage: ^10.3.1
{{/auth}}
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^4.0.1
  json_serializable: ^6.13.0
  drift_dev: ^2.31.0
  auto_route_generator: ^10.5.0

flutter:
  uses-material-design: true